blueprints/qa.py
from flask import Blueprint,render_template,g,request,redirect,url_for,flash
from decorators import login_required
from .forms import UploadForm
from models import UploadDataModel,UserModel
from exts import db
from sqlalchemy import or_

bp = Blueprint("qa",__name__,url_prefix="/")

@bp.route("/")
def index():
    data = UploadDataModel.query.order_by(UploadDataModel.create_time.desc()).all()
    return render_template('index.html',data=data)

@bp.route("/DataTrans/uploadData",methods=["GET","POST"])
@login_required # 相当于 login_required(UploadData)
def UploadData():
    # 判断是否已登录，若未登录则跳转至登录页面
    if request.method == "GET":
        return render_template("DataTrans.html")
    else:
        form = UploadForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            from bilstm_crf import call_blicrf
            kwords, syms = call_blicrf(content)
            kw = process_kwords(kwords,syms)
            uploadData = UploadDataModel(title=title,content=content,author=g.user,patient=kw['patient'],age=kw['age'],
                                         gender=kw['gender'],place=kw['place'],relation=kw['relation'],rel_pat=kw['rel_pat'],
                                         onset_time=kw['onset_time'],symptoms=kw['symptoms'],track=kw['track'],town=kw['town'],
                                         province=kw['province'],county=kw['county'],district=kw['district'],city=kw['cities'])
            db.session.add(uploadData)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题或内容格式错误或为空！")
            return redirect(url_for("qa.UploadData"))

def process_kwords(kwords, syms):
    patient = None
    gender = None
    age = None
    place = []
    cities = []
    province = []
    town = []
    county = []
    district = []
    relation = None
    rel_pat = None
    onset_time = None
    symptoms = []
    track = []
    for i in range(len(kwords)):
        if syms[i]=='PAT'and patient==None:
            patient=kwords[i]
        elif syms[i]=='GEN':
            gender=kwords[i]
        elif syms[i]=='AGE':
            age=kwords[i]
        elif syms[i]=='PLACE':
            place.append(kwords[i])
            track.append(kwords[i])
        elif syms[i] == 'CITY':
            cities.append(kwords[i])
            track.append(kwords[i])
        elif syms[i] == 'REL':
            relation = kwords[i]
        elif syms[i] == 'PAT'and patient!=None and rel_pat==None:
            rel_pat = kwords[i]
        elif syms[i] == 'DATE':
            onset_time = kwords[i]
        elif syms[i] == 'SYM':
            symptoms.append(kwords[i])
        elif syms[i] == 'PROVINCE':
            province.append(kwords[i])
            track.append(kwords[i])
        elif syms[i] == 'COUNTY':
            county.append(kwords[i])
            track.append(kwords[i])
        elif syms[i] == 'TOWN':
            town.append(kwords[i])
            track.append(kwords[i])
        elif syms[i] == 'DISTRCT':
            district.append(kwords[i])
            track.append(kwords[i])
    place = ' '.join(place)
    cities = ' '.join(cities)
    symptoms = ' '.join(symptoms)
    province = ' '.join(province)
    county = ' '.join(county)
    town = ' '.join(town)
    district = ' '.join(district)
    track = ' '.join(track)
    kw = {'patient':patient,'age':age,'gender':gender,'place':place,'cities':cities,'province':province,'town':town,
          'county':county,'district':district,'relation':relation,'rel_pat':rel_pat,'onset_time':onset_time,
          'symptoms':symptoms,'track':track}
    for key,value in kw.items():
        if value==' 'or value==None or len(value)==0:
            kw[key]='未知'
    return kw




@bp.route("/DataTrans/Display",methods=["GET"])
@login_required # 相当于 login_required(UploadData)
def Display():
    inf = []
    age_group = []
    people = []
    link = []
    places = []
    place_data = []
    place_stat = {}
    dates = []
    count = UploadDataModel.query.count()
    for i in range(1,count+1):
        line = UploadDataModel.query.filter_by(id=i).first()
        datum = {'id':line.id,'name':line.patient,'gender':line.gender,'age':line.age,'track':line.track,'onset_time':line.onset_time,'symptoms':line.symptoms}
        dates.append(line.create_time.date())
        # 构造关系图数据
        if line.rel_pat != '未知':
            p = line.patient+'('+str(line.id)+')'
            rel_person = {line.rel_pat:60}
            person = {p:40}
            rel = [line.rel_pat,p,line.relation]
            if person not in people:
                people.append(person)
            if rel_person not in people:
                people.append(rel_person)
            if rel not in link:
                link.append(rel)

        age_group.append(line.age)
        place_stat = place_analysis(line.track,place_stat)
        inf.append(datum)
    # 构造折线图数据
    axis,date_count = daily_pat_count(dates)
    # 柱状图数据
    nl = top_n_scores(6, place_stat)
    for n in range(len(nl)):
        places.append(nl[n][0])
        place_data.append(nl[n][1])
    # 饼状图数据
    age_data = age_division(age_group)
    age_div = [age_data['老年人(60岁以上)'],age_data['中年人(45岁-59岁)'],age_data['青年人(18岁-44岁)'],age_data['少年儿童(18岁以下)']]

    return render_template('display.html',axis=axis,data=date_count,people=people,link=link,track_inf=inf,places=places,place_data=place_data,age_data=age_div)


def place_analysis(place_data,place_stat):
    place_list = place_data.split(' ')
    for i in range(len(place_list)):
        if place_list[i] not in place_stat.keys():
            place_stat[place_list[i]] = 1
        elif place_stat[place_list[i]]:
            place_stat[place_list[i]] += 1
    return place_stat

def top_n_scores(n,score_dict):
    lot = [(k,v)for k,v in score_dict.items()]
    nl = []
    while len(lot)>0:
        nl.append(max(lot,key=lambda x:x[1]))
        lot.remove(nl[-1])
    return nl[0:n]

def age_division(age_group):
    age_div = {'老年人(60岁以上)':0,'中年人(45岁-59岁)':0,'青年人(18岁-44岁)':0,'少年儿童(18岁以下)':0}
    for i in range(len(age_group)):
        if age_group[i] != '未知':
            age=int(age_group[i][:-1])
        else:
            continue
        if age >= 60:
            age_div['老年人(60岁以上)'] += 1
        elif age >= 45 and age < 60:
            age_div['中年人(45岁-59岁)'] += 1
        elif age >= 18 and age < 45:
            age_div['青年人(18岁-44岁)'] += 1
        else:
            age_div['少年儿童(18岁以下)'] += 1
    return age_div

def daily_pat_count(dates):
    date_note = {}
    date_key = []
    date_value = []
    for i in range(len(dates)):
        date = str(dates[i])
        if date not in date_note.keys():
            date_note[date] = 1
        else:
            date_note[date] += 1
    for key,value in date_note.items():
        date_key.append(key)
        date_value.append(value)
    return date_key[-5:],date_value[-5:]

@bp.route('/search')
def search():
    # 传递方式: /search/?q=xxx
    q = request.args.get("query")
    # filter_by: 直接使用字段名称; filter: 使用模型.字段名称
    questions = UploadDataModel.query.filter(or_(UploadDataModel.title.contains(q),
                                                 UploadDataModel.content.contains(q),)).order_by(db.text('-create_time'))

    return render_template("index.html",data=questions)

blueprints/user.py
from flask import Blueprint,render_template,request,redirect,url_for,jsonify,session,flash
from exts import mail
from flask_mail import Message      # 导入邮箱信息
from models import EmailCaptchaModel,UserModel
import string
import random
from datetime import datetime
from exts import db
from .forms import RegisterForm,LoginForm
from werkzeug.security import generate_password_hash,check_password_hash

bp = Blueprint("user",__name__,url_prefix="/user")

@bp.route("/login",methods=['GET','POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password,password):
                # 若登录成功，将user_id存入session
                session['user_id'] = user.id
                return redirect("/")
            else: # 若未登陆成功，则重定向回登录页面
                flash("邮箱和密码不匹配！")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱或密码格式错误！")
            return redirect(url_for("user.login"))

# 退出登录
@bp.route("/logout")
def logout():
    # 清除session数据
    session.clear()
    return redirect(url_for('user.login'))



@bp.route("/register",methods=['GET','POST'])
def register():
    if request.method == "GET":
        return render_template("register.html")
    else:   # 以下代码需要在POST请求下执行
        # 获取前端form表单上传的数据
        form = RegisterForm(request.form)
        if form.captcha.data != None:
            input_captcha = form.captcha.data
            email = form.email.data
            captcha = EmailCaptchaModel.query.filter_by(email=email).first().captcha
            if form.validate() and input_captcha==captcha:  # 同时也使用了validate_captcha和validate_email函数验证
                # 获取相应数据
                username = form.username.data
                password = form.password.data
                # 使用MD5(hash)对于用户密码进行加密后存入数据库
                hash_password = generate_password_hash(password)
                # 创建用户
                user = UserModel(email=email, username=username, password=hash_password)
                db.session.add(user)
                db.session.commit()
                # 注册成功则跳转至登录页面
                return redirect(url_for("user.login"))
            else:  # 若验证失败(注册失败)
                flash("注册信息输入有误！")
                return redirect(url_for("user.register"))
        else:
            flash("验证码输入有误！")
            return redirect(url_for("user.register"))

@bp.route("/captcha",methods=['POST'])
def get_captcha():
    # POST方式获取验证码"1248164362@qq.com"
    email = request.form.get('email')
    # 生成验证码
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters,4))
    if email:
        message = Message(
            subject="邮箱测试",
            recipients=[email],
            body=f"【病例轨迹研究所】您的注册验证码是：{captcha}，请不要告诉任何人哦！"
        )
        # 发送对应body内容至对应邮箱
        mail.send(message)
        # 判断邮箱是否已存在，若存在则更新验证码和接收验证码时间
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else: # 若不存在
            captcha_model = EmailCaptchaModel(email=email,captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        print("captcha:",captcha)
        # code:200,表示请求成功
        return jsonify({"code": 200})
    else:
        # code:400,表示客户端错误
        return jsonify({"code": 400,"message": "请先输入邮箱！"})


templates/DataTrans.html
{% extends "base.html" %}

{% block title %}
    轨迹数据转化
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 30px;">
        <div class="col"></div>
        <div class="col-8">
            <h2 style="text-align: center;margin-bottom: 20px;">病例通报文本上传</h2>
            <form action="{{ url_for("qa.UploadData") }}" method="post">
                <div class="form-group">
                    <input type="text" name="title" class="form-control" placeholder="请输入标题">
                </div>
                <div class="form-group">
                    <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
                </div>
                {%  for message in get_flashed_messages() %}
                      <div class="form-group">
                         <div class="text-danger">{{ message }}</div>
                      </div>
                {% endfor %}
                <div class="form-group" style="text-align: right">
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.4.6.min.css") }}">
    <link rel="stylesheet" href="{{ url_for('static',filename="css/init.css") }}">
    {% block header %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
         <a class="navbar-brand" href="#">病例轨迹研究所</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for("qa.UploadData")}}">文本上传</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for("qa.Display")}}">病例轨迹</a>
              </li>

                <li class="nav-item ml-3">
                    <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('qa.search') }}">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="query">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>
              <ul class="navbar-nav">
                {% if user %}
                  <li class="nav-item active">
                      <span class="nav-link">{{ user.username }}</span>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{{ url_for('user.logout')}}">退出登录</a>
                  </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for("user.login")}}">登录 </a>
                    </li>
                   <li class="nav-item">
                        <a class="nav-link" href="{{url_for("user.register")}}">注册</a>
                   </li>
                {% endif %}
            </ul>
          </div>
    </div>
</nav>
<div class="container">
    {% block body %}{% endblock %}
</div>
<footer style="width: 100%;height: 30px;background-color: #f7f7f7;">
    <div style="text-align: center;margin-bottom: 5px;">
        <a href="#top" target="_self" style="color: #696969;">返回顶部</a>
    </div>

</footer>
</body>
{% block script %}{% endblock %}
</html>

templates/display.html
{% extends "base.html" %}

{% block title %}轨迹研究所-登录{% endblock %}

{% block header %}
    <style>
        h2 {text-align:center;margin-bottom: 30px;margin-top: 30px;}
        div.graph {width:600px; height: 400px;margin:0 auto;margin-bottom: 50px;}
    </style>
    <script src="{{ url_for('static',filename="jquery/jquery.3.6.min.js") }}"></script>
    <script src="{{ url_for('static',filename="js/echarts.min5.0.js") }}"></script>
{% endblock %}

{% block body %}
    <div class="row mt-4">
      <div class="col"></div>
      <div class="col" style="background-color: #fbfcfc;">
          <h2>病例轨迹统计</h2>

                   <div id="chart1"  class="graph" ></div>
          <div id="main"  class="graph" ></div>
          <div id="pie"  class="graph" ></div>



          <script type="text/javascript">

              var myChart = echarts.init(document.getElementById('chart1'));
              {#var xis = [{% for item in xis.1 %}{{ item }},{% endfor %}];#}
              var option = {
                    title:{
                        text:'近5日病例发布折线图'
                    },
                    tooltip:{},
                    legend:{
                        data:['访客来源']
                    },
                    xAxis:{
                        data:{{ axis|safe }}
                    },
                    yAxis:{
                    },
                    series:[{
                        name:'发布病例数量',
                        type:'line',
                        areaStyle: {
                            normal: {}
                        },
                        data:{{ data|safe }}
                        {#data:[600,310,200,800]#}
                    }]
                };

              myChart.setOption(option);
          </script>


          <script type="text/javascript">
              // 基于准备好的dom，初始化echarts实例
              var myChart = echarts.init(document.getElementById('main'));
              // 指定图表的配置项和数据
              var option = {
                  title: {
                      text: '经过地点人数柱状图'
                  },
                  tooltip: {},
                  legend: {
                      data: ['地点']
                  },
                  xAxis: {
                      data: {{ places | safe }},
                          {#["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]#}
                      axisLabel: {
	                                  // 标签的显示间隔，0为强制显示全部，n为隔n标签显示一个标签
		                                interval: 0,
                                    rotate: "50"
                      }
                  },
                  yAxis: {},
                  series: [{
                      name: '到访病例数量',
                      type: 'bar',
                      data: {{ place_data | safe }}
                          {#[5, 20, 36, 10, 10, 20]#}
                  }]
              };

              // 使用刚指定的配置项和数据显示图表。
              myChart.setOption(option);
          </script>
          <div id="dataid" d="{{age_data}}" style="display:none"></div>
          <script type="text/javascript">
              // 基于准备好的dom，初始化echarts实例
              var myChart = echarts.init(document.getElementById('pie'));
              var age_data = document.getElementById('dataid').getAttribute('d');
              console.log(age_data);
              var age_div =new Array();
              age_div[0]={value:parseInt(age_data[1]),name:'老年人(60岁以上)'};
              age_div[1]={value:parseInt(age_data[4]),name:'中年人(45岁-59岁)'};
              age_div[2]={value:parseInt(age_data[7]),name:'青年人(18岁-44岁)'};
              age_div[3]={value:parseInt(age_data[10]),name:'少年儿童(18岁以下)'};

              console.log(age_div);

              myChart.setOption({
                  title: {
                      text: '患者年龄分布图'
                  },
                  series: [
                      {
                          name: '访问来源',
                          type: 'pie',    // 设置图表类型为饼图
                          radius: '50%',  // 饼图的半径，外半径为可视区尺寸（容器高宽中较小一项）的 55% 长度。
                          data: age_div,
                          label: {
                              normal: {
                                  show: true,
                                  formatter: '{b}:{c}: ({d}%)',//多值的嵌套
                              }
                          }
                      }
                  ]
              })
          </script>

          <div id="relationship" class="graph" style="border:1px solid #ccc;"></div>
            <script type="text/javascript">
                var myChart = echarts.init(document.getElementById('relationship'));
                var people = {{ people|safe }};
                var raw_link = {{ link|safe }};
                var data = [],link=[];
                for(var i=0;i<people.length;i++){
                    console.log("raw_data:"+Object.keys(people[i])+Object.values(people[i]));
                    data.push({name:Object.keys(people[i])[0],symbolSize:Object.values(people[i])[0]});
                }
                for(var j=0;j<raw_link.length;j++){
                    link.push({source:raw_link[j][0],target:raw_link[j][1],name:raw_link[j][2]});
                }
                console.log(data);
                console.log(link);

                var obj = {
                    relationList: {
                        data:data,
                        link: link,
                    }

                }

                var relationData = obj.relationList;
                var data = relationData.data;
                var link = relationData.link;
                option = {
                    title:{
                        text:'患者关系图'
                    },
                    series: [{
                        type: 'graph', // 类型:关系图
                        layout: 'force', //图的布局，类型为力导图
                        symbolSize: 5, // 调整节点的大小
                        roam: true, // 是否开启鼠标缩放和平移漫游。默认不开启。如果只想要开启缩放或者平移,可以设置成 'scale' 或者 'move'。设置成 true 为都开启
                        edgeSymbol: ['circle', 'arrow'],
                        edgeSymbolSize: [1, 2],
                        edgeLabel: {
                            normal: {
                                textStyle: {
                                    fontSize: 15
                                }
                            }
                        },
                        force: {
                            repulsion: 1000,
                            edgeLength: [10, 40]
                        },
                        draggable: true,
                        lineStyle: {
                            normal: {
                                width: 2,
                                color: '#1C1C1C'
                            }
                        },
                        edgeLabel: {
                            normal: {
                                color: '#1C1C1C',//线上的字体颜色
                                show: true,
                                formatter: function (x) {
                                    return x.data.name;
                                }
                            }
                        },
                        label: {
                            normal: {
                                show: true,
                                textStyle: {}
                            }
                        },

                        // 数据
                        data: data,
                        links: link,
                        color: ['#FF4500']
                    }]
                };
                myChart.setOption(option);
            </script>

          <div class="inf-table" style="margin-bottom: 100px;width: 900px;">
              <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col"style="width: 80px;">患者</th>
                      <th scope="col"style="width: 60px;">性别</th>
                      <th scope="col"style="width: 60px;">年龄</th>
                      <th scope="col">轨迹</th>
                      <th scope="col"style="width: 100px;">发病时间</th>
                      <th scope="col"style="width: 100px;">发病症状</th>
                    </tr>
                  </thead>
                  <tbody>
                   {% for datum in track_inf  %}
                    <tr>
                        {% for k,item in datum.items() %}
                            {% if k=='id' %}
                                <th scope="row">{{ item }}</th>
                            {% else %}
                                <td>{{ item }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                   {% endfor %}
                  </tbody>
                </table>
          </div>

      </div>
      <div class="col"></div>
    </div>

{% endblock %}

{% block script %}

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}轨迹研究所-首页{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{{ url_for('static',filename="css/index.css") }}">
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-8" style="background-color: #fbfcfc;">
            <h4 style="text-align: center;margin-top: 20px;">确诊病例通报</h4>
            <ul class="TrackData-ul" >
                {% for datum in data %}
                    <li style="background-color: #fbfcfc;border-bottom:1px solid #DCDCDC;">
                    <div class="data-main">
                        <div class="data-title"><a href="#">{{ datum.title }}</a></div>
                        <div class="data-content">{{ datum.content }}</div>
                        <div class="data-detail">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                            </svg>
                            <span class="data-author">{{ datum.author.username }}</span>
                            <span class="data-time">{{ datum.create_time }}</span>
                        </div>
                    </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>

    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}轨迹研究所-登录{% endblock %}

{% block header %}
    <style>
        h2 {text-align:center}
    </style>
{% endblock %}

{% block body %}
    <div class="row mt-5">
      <div class="col"></div>
      <div class="col">
          <h2>用户登录</h2>
      <form action="{{ url_for("user.login") }}" method="POST">
        <div class="form-group">
            <label for="exampleInputEmail1">邮箱</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            <input type="password" class="form-control" name="password">
            <small id="emailHelp" class="form-text text-muted">还没有注册？请前往注册</small>
        </div>

              {%  for message in get_flashed_messages() %}
                  <div class="form-group">
                    <div class="text-danger">{{ message }}</div>
                  </div>
              {% endfor %}

          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">立即登录</button>
          </div>
    </form>
      </div>
      <div class="col"></div>
    </div>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}轨迹研究所-注册{% endblock %}

{% block header %}
    <script src="{{ url_for('static',filename="jquery/jquery.3.6.min.js") }}"></script>
    <script src="{{ url_for('static',filename="js/register.js") }}"></script>
    <style>
        h3 {text-align:center}
    </style>
{% endblock %}

{% block body %}
    <div class="row mt-3">
      <div class="col"></div>
      <div class="col">
          <h3>用户注册</h3>
      <form method="POST" action="{{ url_for('user.register') }}">
          <div class="form-group">
            <label for="exampleInputEmail1">用户名</label>
            <input type="text" class="form-control" name="username">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">邮箱</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
            <small id="emailHelp" class="form-text text-muted">我们不会把您的邮箱用于其他用途</small>
        </div>

         <div class="form-group">
            <label for="exampleInputEmail1">验证码</label>
            <div class="input-group">
                <input type="text" class="form-control" name="captcha">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">确认密码</label>
            <input type="password" class="form-control" name="password_confirm">
        </div>

           {%  for message in get_flashed_messages() %}
                  <div class="form-group">
                    <div class="text-danger">{{ message }}</div>
                  </div>
              {% endfor %}

          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">注册</button>
          </div>
    </form>
    </div>
      <div class="col"></div>
    </div>
{% endblock %}